import { alpha } from "@mui/material";
import { palette } from "@/common/theme";

export const styles = {
  card: {
    p: 3,
    height: "100%",
    display: "flex",
    flexDirection: "column",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    mb: 3,
  },
  title: {
    fontWeight: 600,
    display: "flex",
    alignItems: "center",
    gap: 1.5,
  },
  titleIcon: {
    p: 0.8,
    borderRadius: 1.5,
    bgcolor: alpha(palette.info.main, 0.1),
    display: "flex",
    color: palette.info.main,
  },
  feedLink: {
    color: palette.info.light,
    display: "flex",
    alignItems: "center",
    gap: 0.5,
    cursor: "pointer",
    fontWeight: 500,
    "&:hover": { color: palette.info.main },
  },
  sourceBadge: {
    px: 1,
    py: 0.4,
    borderRadius: 1,
    bgcolor: alpha(palette.text.primary, 0.04),
    fontSize: "0.65rem",
    fontWeight: 600,
    color: "text.secondary",
  },
  categoryLabel: (color: string) => ({
    fontSize: "0.7rem",
    fontWeight: 800,
    color,
    textTransform: "uppercase",
    letterSpacing: "0.8px",
  }),
  articleTitle: {
    fontWeight: 700,
    lineHeight: 1.3,
    color: "text.primary",
    mb: 1,
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
  },
  articleDescription: {
    color: "text.secondary",
    lineHeight: 1.4,
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
  },
  externalIcon: {
    position: "absolute",
    bottom: 12,
    right: 12,
    opacity: 0,
    transition: "all 0.3s ease",
  },
  skeletonCard: {
    p: 2.5,
    borderRadius: 3,
    bgcolor: alpha(palette.text.primary, 0.02),
    border: `1px solid ${alpha(palette.text.primary, 0.05)}`,
    display: "flex",
    flexDirection: "column",
    gap: 1.5,
  },
};
