import { type Theme, alpha } from "@mui/material";

export const makeStyles = (theme: Theme) => ({
  inputCard: {
    position: "relative",
    overflow: "hidden",
    p: { xs: 4, md: 5 },
    borderRadius: 6,
    background: alpha(theme.palette.background.paper, 0.4),
    backdropFilter: "blur(12px)",
    border: `1px solid ${alpha(theme.palette.primary.light, 0.1)}`,
  },
  iconCenter: {
    display: "flex",
    justifyContent: "center",
    mb: 3,
  },
  iconWrapper: {
    width: 64,
    height: 64,
    borderRadius: 4,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    bgcolor: alpha(theme.palette.primary.main, 0.12),
    color: theme.palette.primary.light,
  },
  title: {
    fontWeight: 700,
    textAlign: "center",
    mb: 1,
    background: `linear-gradient(135deg, ${theme.palette.primary.light}, ${theme.palette.accent})`,
    backgroundClip: "text",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
  },
  subtitle: {
    color: theme.palette.text.secondary,
    textAlign: "center",
    mb: 4,
  },
  textField: {
    mb: 2,
  },
  nameField: {
    mb: 3,
  },
  errorText: {
    color: theme.palette.error.light,
    mb: 2,
    textAlign: "center",
  },
  generatingCard: {
    minHeight: "80vh",
    p: { xs: 4, md: 5 },
    borderRadius: 6,
    background: alpha(theme.palette.background.paper, 0.4),
    backdropFilter: "blur(12px)",
    border: `1px solid ${alpha(theme.palette.primary.light, 0.1)}`,
  },
  generatingLayout: {
    display: "grid",
    gridTemplateColumns: { xs: "1fr", md: "minmax(0, 0.85fr) minmax(0, 1fr)" },
    gap: { xs: 0, md: 5 },
    alignItems: "center",
  },
  cardSwapStage: {
    display: { xs: "none", md: "flex" },
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    height: 560,
    minHeight: 560,
  },
  cardSwapInner: {
    position: "relative",
    width: 540,
    height: 380,
  },
  infoCard: (accent: string) => ({
    p: 4,
    width: "100%",
    height: "100%",
    position: "relative",
    display: "flex",
    flexDirection: "column",
    gap: 1.75,
    overflow: "hidden",
    borderRadius: 4,
    border: `1px solid ${alpha(accent, 0.22)}`,
    background: `
			radial-gradient(circle at 0% 0%, ${alpha(accent, 0.32)} 0%, transparent 55%),
			radial-gradient(circle at 100% 100%, ${alpha(accent, 0.16)} 0%, transparent 50%),
			linear-gradient(160deg, ${alpha(theme.palette.background.paper, 0.96)} 0%, ${alpha(theme.palette.background.default, 0.98)} 100%)
		`,
    boxShadow: `
			0 32px 72px -12px ${alpha(theme.palette.common.black, 0.6)},
			0 0 0 1px ${alpha(accent, 0.08)} inset,
			0 0 80px ${alpha(accent, 0.12)} inset,
			0 12px 32px ${alpha(accent, 0.22)}
		`,
    color: theme.palette.text.primary,
  }),
  infoCardIcon: (accent: string) => ({
    width: 52,
    height: 52,
    borderRadius: 2.5,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: `linear-gradient(135deg, ${alpha(accent, 0.35)}, ${alpha(accent, 0.12)})`,
    border: `1px solid ${alpha(accent, 0.4)}`,
    color: accent,
    boxShadow: `0 8px 18px ${alpha(accent, 0.25)}`,
  }),
  infoCardTitle: (accent: string) => ({
    fontWeight: 700,
    color: alpha(accent, 0.95),
    letterSpacing: "-0.01em",
  }),
  infoCardBody: {
    color: theme.palette.text.primary,
    opacity: 0.85,
    lineHeight: 1.55,
  },
  generatingTitle: {
    fontWeight: 700,
    mb: 1,
    background: `linear-gradient(135deg, ${theme.palette.primary.light}, ${theme.palette.accent})`,
    backgroundClip: "text",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
  },
  generatingSubtitle: {
    color: theme.palette.text.secondary,
    mb: 4,
  },
  stagesWrapper: {
    pl: 1,
  },
});
