import { type Theme, alpha, type SxProps } from '@mui/material';
import { palette } from '@/common/theme';

export const makeStyles = (): Record<string, SxProps<Theme>> => ({
	container: {
		mb: 6,
		position: 'relative',
	},
	content: {
		position: 'relative',
		overflow: 'hidden',
		borderRadius: 8,
		p: { xs: 5, md: 8 },
		background: `linear-gradient(135deg, ${alpha(palette.background.paper, 0.8)} 0%, ${alpha(palette.background.paper, 0.4)} 100%)`,
		backdropFilter: 'blur(16px)',
		border: `1px solid ${alpha(palette.info.light, 0.1)}`,
		boxShadow: `0 24px 48px ${alpha(palette.background.default, 0.4)}`,
	},
	gradientOrb: {
		position: 'absolute',
		top: -120,
		right: -120,
		width: 400,
		height: 400,
		borderRadius: '50%',
		background: `radial-gradient(circle, ${alpha(palette.info.main, 0.15)} 0%, transparent 70%)`,
		filter: 'blur(60px)',
		pointerEvents: 'none',
		zIndex: 0,
	},
	secondaryOrb: {
		position: 'absolute',
		bottom: -150,
		left: -100,
		width: 350,
		height: 350,
		borderRadius: '50%',
		background: `radial-gradient(circle, ${alpha(palette.primary.main, 0.1)} 0%, transparent 70%)`,
		filter: 'blur(50px)',
		pointerEvents: 'none',
		zIndex: 0,
	},
	title: {
		fontWeight: 900,
		mb: 2,
		background: `linear-gradient(135deg, ${palette.text.primary} 0%, ${palette.info.light} 50%, ${palette.primary.light} 100%)`,
		backgroundClip: 'text',
		WebkitBackgroundClip: 'text',
		WebkitTextFillColor: 'transparent',
		fontSize: { xs: '2.5rem', md: '3.5rem' },
		letterSpacing: '-1.5px',
		lineHeight: 1.1,
		position: 'relative',
		zIndex: 1,
	},
	subtitle: {
		color: palette.text.secondary,
		mb: 4,
		maxWidth: 540,
		fontSize: '1.1rem',
		lineHeight: 1.6,
		position: 'relative',
		zIndex: 1,
		opacity: 0.9,
	},
	badge: {
		display: 'inline-flex',
		alignItems: 'center',
		gap: 1,
		px: 2,
		py: 0.5,
		borderRadius: 100,
		bgcolor: alpha(palette.info.main, 0.1),
		border: `1px solid ${alpha(palette.info.main, 0.2)}`,
		color: palette.info.light,
		mb: 3,
		fontSize: '0.75rem',
		fontWeight: 700,
		textTransform: 'uppercase',
		letterSpacing: '1px',
		position: 'relative',
		zIndex: 1,
	},
});
