import { GenerateTopicRoadmapUseCase } from '../../../src/features/roadmap/app/usecases/generate-topic-roadmap.usecase';
import { FakeRoadmapRepository } from '../_fakes/repositories';

describe('GenerateTopicRoadmapUseCase', () => {
  let roadmapRepo: FakeRoadmapRepository;
  let topicConceptGenerationService: {
    generateConceptsFromTopic: jest.Mock;
  };
  let roadmapGenerationService: {
    generateLearningPath: jest.Mock;
  };
  let useCase: GenerateTopicRoadmapUseCase;

  beforeEach(() => {
    roadmapRepo = new FakeRoadmapRepository();
    topicConceptGenerationService = {
      generateConceptsFromTopic: jest
        .fn()
        .mockResolvedValue({ concepts: [], relationships: [] }),
    };
    roadmapGenerationService = {
      generateLearningPath: jest.fn(),
    };

    useCase = new GenerateTopicRoadmapUseCase(
      roadmapRepo,
      topicConceptGenerationService as never,
      roadmapGenerationService as never,
    );
  });

  it('uses the standard autogenerated title for plain topics', async () => {
    const result = await useCase.execute({ topic: 'React' });

    expect(result.title).toBe('Learn React');
  });

  it('avoids duplicating Learn when the topic already starts with Learn', async () => {
    const result = await useCase.execute({ topic: 'Learn React' });

    expect(result.title).toBe('Learn React');
  });

  it('keeps an explicit title unchanged', async () => {
    const result = await useCase.execute({
      topic: 'Learn React',
      title: 'React Fundamentals',
    });

    expect(result.title).toBe('React Fundamentals');
  });
});
