import { alpha, type SxProps } from '@mui/material';
import type { Theme } from '@mui/material';

export const makeStyles = (theme: Theme, statusColor: string) => ({
	container: {
		display: 'flex',
		gap: { xs: 1.5, sm: 2.5 },
	},
	indicatorColumn: {
		display: 'flex',
		flexDirection: 'column',
		alignItems: 'center',
		pt: { xs: 1.5, sm: 2.5 },
	},
	dotContainer: {
		position: 'relative',
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'center',
	},
	pulseRing: {
		position: 'absolute',
		width: { xs: 32, sm: 40 },
		height: { xs: 32, sm: 40 },
		borderRadius: '50%',
		bgcolor: alpha(statusColor, 0.3),
	},
	dot: (isCompleted: boolean) => ({
		width: { xs: 32, sm: 40 },
		height: { xs: 32, sm: 40 },
		borderRadius: '50%',
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'center',
		bgcolor: isCompleted ? statusColor : alpha(statusColor, 0.15),
		color: isCompleted ? theme.palette.background.default : statusColor,
		transition: 'all 0.3s ease',
		zIndex: 1,
		fontSize: { xs: '0.8rem', sm: '1rem' },
	}),
	connector: (isCompleted: boolean) => ({
		flex: 1,
		width: 2,
		mt: 1,
		bgcolor:
			isCompleted ?
				alpha(theme.palette.success.light, 0.3)
			:	alpha(theme.palette.divider, 1),
		transition: 'background-color 0.3s ease',
	}),
	card: {
		flex: 1,
		borderRadius: 4,
		overflow: 'hidden',
		background: alpha(theme.palette.background.paper, 0.4),
		backdropFilter: 'blur(12px)',
		border: `1px solid ${alpha(theme.palette.primary.light, 0.1)}`,
		transition: 'all 0.3s ease',
		'&:hover': {
			borderColor: alpha(theme.palette.primary.light, 0.25),
		},
	},
	header: {
		p: { xs: 1.5, sm: 2.5 },
		cursor: 'pointer',
		display: 'flex',
		alignItems: 'flex-start',
		justifyContent: 'space-between',
		gap: 2,
	},
	titleRow: {
		display: 'flex',
		alignItems: 'center',
		gap: 1,
		mb: 1,
		flexWrap: 'wrap',
	},
	title: {
		fontWeight: 600,
		color: theme.palette.text.primary,
		fontSize: { xs: '1.05rem', sm: '1.25rem' },
		lineHeight: 1.3,
	},
	stepChip: {
		height: 24,
		fontSize: '0.7rem',
		fontWeight: 600,
		bgcolor: alpha(theme.palette.primary.main, 0.1),
		color: theme.palette.primary.light,
	},
	description: (expanded: boolean) => ({
		color: theme.palette.text.secondary,
		mb: 1.5,
		fontSize: { xs: '0.9rem', sm: '0.95rem' },
		lineHeight: 1.5,
		display: '-webkit-box',
		WebkitLineClamp: expanded ? 999 : 2,
		WebkitBoxOrient: 'vertical',
		overflow: 'hidden',
	}),
	metaRow: {
		display: 'flex',
		gap: 2,
		alignItems: 'center',
		flexWrap: 'wrap',
	},
	statusChip: (color: string) => ({
		height: 24,
		fontSize: '0.7rem',
		fontWeight: 700,
		bgcolor: alpha(color, 0.12),
		color: color,
	}),
	actionsContainer: {
		display: 'flex',
		alignItems: 'center',
		gap: 0.5,
		flexShrink: 0,
		pt: 0.5,
	},
	actionButton: {
		color: theme.palette.primary.light,
		padding: { xs: 0.5, sm: 1 },
		'&:hover': {
			bgcolor: alpha(theme.palette.primary.main, 0.1),
		},
	},
	skipButton: {
		color: theme.palette.text.secondary,
		padding: { xs: 0.5, sm: 1 },
		'&:hover': {
			bgcolor: alpha(theme.palette.text.secondary, 0.1),
		},
	},
	expandedContent: {
		px: { xs: 1.5, sm: 2.5 },
		pb: { xs: 1.5, sm: 2.5 },
		display: 'flex',
		flexDirection: 'column',
		gap: 2,
	},
	infoBox: (color: string) => ({
		display: 'flex',
		alignItems: 'flex-start',
		gap: 1.5,
		p: { xs: 1.5, sm: 2 },
		borderRadius: 3,
		bgcolor: alpha(color, 0.06),
		border: `1px solid ${alpha(color, 0.12)}`,
		mt: { xs: 1, sm: 0 },
	}),
	infoLabel: (color: string) => ({
		fontWeight: 700,
		color: color,
		display: 'block',
		mb: 0.5,
		fontSize: '0.85rem',
		textTransform: 'uppercase',
		letterSpacing: '0.05em',
	}),
});
