export enum UserRole {
  ADMIN = 'ADMIN',
  USER = 'USER',
}

export class User {
  constructor(
    public readonly id: string,
    public readonly email: string,
    public readonly name: string,
    public readonly role: UserRole,
    public readonly avatarUrl?: string,
    public readonly isActive: boolean = true,
    public readonly isVerified: boolean = false,
    public readonly verificationToken: string | null = null,
    public readonly passwordHash: string | null = null,
    public readonly googleId: string | null = null,
    public readonly createdAt: Date = new Date(),
    public readonly updatedAt: Date = new Date(),
  ) {}

  static create(id: string, email: string, name: string, role: UserRole = UserRole.USER, passwordHash: string | null = null): User {
    // New users are unverified by default and should have a token generated by the service
    return new User(id, email, name, role, undefined, true, false, null, passwordHash);
  }

  updateAvatar(url: string): User {
    return new User(
      this.id,
      this.email,
      this.name,
      this.role,
      url,
      this.isActive,
      this.isVerified,
      this.verificationToken,
      this.passwordHash,
      this.googleId,
      this.createdAt,
      new Date(),
    );
  }

  verify(): User {
    return new User(
      this.id,
      this.email,
      this.name,
      this.role,
      this.avatarUrl,
      this.isActive,
      true, // isVerified
      null, // verificationToken
      this.passwordHash,
      this.googleId,
      this.createdAt,
      new Date(),
    );
  }

  withVerificationToken(token: string): User {
    return new User(
      this.id,
      this.email,
      this.name,
      this.role,
      this.avatarUrl,
      this.isActive,
      this.isVerified,
      token,
      this.passwordHash,
      this.googleId,
      this.createdAt,
      new Date(),
    );
  }
}
