import { Category } from '../../category/entities/category.entity';

export enum UserRole {
  ADMIN = 'ADMIN',
  USER = 'USER',
}

export enum OnboardingStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  SKIPPED = 'SKIPPED',
}

export class User {
  constructor(
    public readonly id: string,
    public readonly email: string,
    public readonly name: string,
    public readonly role: UserRole,
    public readonly avatarUrl?: string,
    public readonly isActive: boolean = true,
    public readonly isVerified: boolean = false,
    public readonly verificationToken: string | null = null,
    public readonly passwordHash: string | null = null,
    public readonly googleId: string | null = null,
    public readonly learningGoal: string | null = null,
    public readonly onboardingStatus: OnboardingStatus = OnboardingStatus.PENDING,
    public readonly interests: Category[] = [],
    public readonly createdAt: Date = new Date(),
    public readonly updatedAt: Date = new Date(),
  ) {}

  static create(id: string, email: string, name: string, role: UserRole = UserRole.USER, passwordHash: string | null = null): User {
    // New users are unverified by default and should have a token generated by the service
    return new User(id, email, name, role, undefined, true, false, null, passwordHash, null, null, OnboardingStatus.PENDING);
  }

  updateAvatar(url: string): User {
    return new User(
      this.id,
      this.email,
      this.name,
      this.role,
      url,
      this.isActive,
      this.isVerified,
      this.verificationToken,
      this.passwordHash,
      this.googleId,
      this.learningGoal,
      this.onboardingStatus,
      this.interests,
      this.createdAt,
      new Date(),
    );
  }

  /**
   * Partial update for profile fields (name, learningGoal, avatarUrl)
   */
  withPartialUpdate(updates: { name?: string; learningGoal?: string; avatarUrl?: string }): User {
    return new User(
      this.id,
      this.email,
      updates.name ?? this.name,
      this.role,
      updates.avatarUrl ?? this.avatarUrl,
      this.isActive,
      this.isVerified,
      this.verificationToken,
      this.passwordHash,
      this.googleId,
      updates.learningGoal ?? this.learningGoal,
      this.onboardingStatus,
      this.interests,
      this.createdAt,
      new Date(),
    );
  }

  updateProfile(goal: string, interests: Category[]): User {
      return new User(
        this.id,
        this.email,
        this.name,
        this.role,
        this.avatarUrl,
        this.isActive,
        this.isVerified,
        this.verificationToken,
        this.passwordHash,
        this.googleId,
        goal,
        OnboardingStatus.COMPLETED,
        interests,
        this.createdAt,
        new Date()
      );
  }

  verify(): User {
    return new User(
      this.id,
      this.email,
      this.name,
      this.role,
      this.avatarUrl,
      this.isActive,
      true, // isVerified
      null, // verificationToken
      this.passwordHash,
      this.googleId,
      this.learningGoal,
      this.onboardingStatus,
      this.interests,
      this.createdAt,
      new Date(),
    );
  }

  withVerificationToken(token: string): User {
    return new User(
      this.id,
      this.email,
      this.name,
      this.role,
      this.avatarUrl,
      this.isActive,
      this.isVerified,
      token,
      this.passwordHash,
      this.googleId,
      this.learningGoal,
      this.onboardingStatus,
      this.interests,
      this.createdAt,
      new Date(),
    );
  }

  completeOnboarding(goal: string, interests: Category[]): User {
    return new User(
      this.id,
      this.email,
      this.name,
      this.role,
      this.avatarUrl,
      this.isActive,
      this.isVerified,
      this.verificationToken,
      this.passwordHash,
      this.googleId,
      goal,
      OnboardingStatus.COMPLETED,
      interests,
      this.createdAt,
      new Date(),
    );
  }

  skipOnboarding(): User {
    return new User(
      this.id,
      this.email,
      this.name,
      this.role,
      this.avatarUrl,
      this.isActive,
      this.isVerified,
      this.verificationToken,
      this.passwordHash,
      this.googleId,
      this.learningGoal,
      OnboardingStatus.SKIPPED,
      this.interests,
      this.createdAt,
      new Date(),
    );
  }

  resetOnboarding(): User {
    return new User(
      this.id,
      this.email,
      this.name,
      this.role,
      this.avatarUrl,
      this.isActive,
      this.isVerified,
      this.verificationToken,
      this.passwordHash,
      this.googleId,
      null, // Clear learning goal
      OnboardingStatus.PENDING,
      [], // Clear interests
      this.createdAt,
      new Date(),
    );
  }
}
