import { type Theme, alpha } from "@mui/material";

export const makeStyles = (theme: Theme) => ({
  card: {
    minHeight: { xs: "auto", md: "min(70vh, 600px)" },
    maxWidth: { xs: "100%", md: 1160 },
    mx: "auto",
    borderRadius: { xs: 4, md: 7 },
    py: { xs: 2.5, sm: 4, md: 5.5 },
    px: { xs: 1.5, sm: 4, md: 8 },
    position: "relative",
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
    gap: { xs: 3.5, md: 4.5 },
    background: `linear-gradient(180deg, ${alpha(theme.palette.background.paper, 0.72)} 0%, ${alpha(theme.palette.background.paper, 0.5)} 100%)`,
    backdropFilter: "blur(18px)",
    border: `1px solid ${alpha(theme.palette.common.white, 0.08)}`,
    boxShadow: `inset 0 1px 0 ${alpha(theme.palette.common.white, 0.08)}, 0 28px 80px ${alpha("#000", 0.28)}`,
    "&::before": {
      content: '""',
      position: "absolute",
      inset: 0,
      borderRadius: "inherit",
      background: `radial-gradient(circle at 16% 22%, ${alpha(theme.palette.primary.light, 0.16)} 0%, transparent 28%), radial-gradient(circle at 82% 76%, ${alpha(theme.palette.purple.light, 0.12)} 0%, transparent 24%), linear-gradient(135deg, ${alpha(theme.palette.common.white, 0.04)} 0%, transparent 46%)`,
      pointerEvents: "none",
    },
  },
  orb1: {
    position: "absolute",
    top: "-42px",
    right: "-24px",
    width: 280,
    height: 180,
    borderRadius: "50%",
    background: alpha(theme.palette.purple.main, 0.12),
    filter: "blur(54px)",
    transform: "rotate(-14deg)",
    zIndex: 0,
    pointerEvents: "none",
  },
  orb2: {
    position: "absolute",
    bottom: "-34px",
    left: "-12px",
    width: 240,
    height: 160,
    borderRadius: "50%",
    background: alpha(theme.palette.accent as string, 0.1),
    filter: "blur(48px)",
    transform: "rotate(18deg)",
    zIndex: 0,
    pointerEvents: "none",
  },
  contentWrapper: {
    position: "relative",
    zIndex: 1,
    maxWidth: 620,
    px: { xs: 0.5, sm: 0 },
  },
  eyebrow: {
    display: "inline-flex",
    alignItems: "center",
    gap: 10,
    textTransform: "uppercase",
    letterSpacing: "0.22em",
    color: alpha(theme.palette.text.secondary, 0.88),
    mb: 1.25,
    fontWeight: 700,
    "&::before": {
      content: '""',
      width: { xs: 24, sm: 36 },
      height: 1,
      borderRadius: 999,
      background: alpha(theme.palette.primary.light, 0.75),
    },
  },
  title: {
    fontWeight: 800,
    background: `linear-gradient(135deg, ${alpha(theme.palette.text.primary, 0.98)} 0%, ${alpha(theme.palette.text.primary, 0.88)} 52%, ${alpha(theme.palette.primary.light, 0.92)} 100%)`,
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
    backgroundClip: "text",
    mb: 1,
    lineHeight: 1.04,
    letterSpacing: "-0.04em",
    maxWidth: 560,
    fontSize: { xs: "2rem", sm: "2.5rem", md: "3rem" },
  },
  subtitle: {
    color: alpha(theme.palette.text.secondary, 0.9),
    maxWidth: 520,
    lineHeight: 1.7,
    fontSize: { xs: "0.94rem", sm: "1rem" },
  },
  bodyLayout: {
    position: "relative",
    zIndex: 1,
    display: "grid",
    gridTemplateColumns: { xs: "1fr", md: "minmax(0, 0.76fr) minmax(0, 1fr)" },
    gap: { xs: 3.25, md: 4.5 },
    alignItems: "stretch",
    flex: 1,
  },
  timelineWrapper: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    gap: 0,
    order: { xs: 2, md: 1 },
    width: "100%",
    mt: { xs: 0.75, md: 0 },
    px: { xs: 1.25, sm: 0.5, md: 0 },
    pr: { md: 2 },
  },
  cardSwapStage: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    order: { xs: 1, md: 2 },
    width: "100%",
    height: { xs: 440, sm: 480, md: 540 },
    minHeight: { xs: 440, sm: 480, md: 540 },
    px: { xs: 0.25, sm: 1, md: 0 },
  },
  cardSwapInner: {
    position: "relative",
    width: 540,
    height: 380,
  },
  infoCard: (accent: string) => ({
    p: 4,
    width: "100%",
    height: "100%",
    position: "relative",
    display: "flex",
    flexDirection: "column",
    gap: 1.75,
    overflow: "hidden",
    borderRadius: 4,
    border: `1px solid ${alpha(accent, 0.22)}`,
    background: `
			radial-gradient(circle at 0% 0%, ${alpha(accent, 0.32)} 0%, transparent 55%),
			radial-gradient(circle at 100% 100%, ${alpha(accent, 0.16)} 0%, transparent 50%),
			linear-gradient(160deg, ${alpha(theme.palette.background.paper, 0.96)} 0%, ${alpha(theme.palette.background.default, 0.98)} 100%)
		`,
    boxShadow: `
			0 32px 72px -12px ${alpha("#000", 0.6)},
			0 0 0 1px ${alpha(accent, 0.08)} inset,
			0 0 80px ${alpha(accent, 0.12)} inset,
			0 12px 32px ${alpha(accent, 0.22)}
		`,
    color: theme.palette.text.primary,
  }),
  infoCardIcon: (accent: string) => ({
    width: 52,
    height: 52,
    borderRadius: 2.5,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: `linear-gradient(135deg, ${alpha(accent, 0.35)}, ${alpha(accent, 0.12)})`,
    border: `1px solid ${alpha(accent, 0.4)}`,
    color: accent,
    boxShadow: `0 8px 18px ${alpha(accent, 0.25)}`,
  }),
  infoCardTitle: (accent: string) => ({
    fontWeight: 700,
    color: alpha(accent, 0.95),
    letterSpacing: "-0.01em",
  }),
  infoCardBody: {
    color: theme.palette.text.primary,
    opacity: 0.85,
    lineHeight: 1.55,
  },
  stageRow: (state: "pending" | "active" | "completed") => ({
    display: "flex",
    flexDirection: "row",
    alignItems: "flex-start",
    opacity: state === "pending" ? 0.45 : 1,
    transition: "opacity 0.6s ease, transform 0.6s ease",
    transform: state === "active" ? "translateX(0)" : "translateX(0)",
  }),
  leftColumn: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    mr: { xs: 1.6, md: 2.2 },
    flexShrink: 0,
  },
  dotWrapper: {
    position: "relative",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  outerHalo: (stageColor: string) => ({
    position: "absolute",
    width: 72,
    height: 72,
    borderRadius: "50%",
    background: alpha(stageColor, 0.15),
    zIndex: 0,
  }),
  innerHalo: (stageColor: string) => ({
    position: "absolute",
    width: 50,
    height: 50,
    borderRadius: "50%",
    background: alpha(stageColor, 0.2),
    zIndex: 0,
  }),
  dot: (state: "pending" | "active" | "completed", stageColor: string) => ({
    position: "relative",
    zIndex: 1,
    width: 34,
    height: 34,
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    transition:
      "background 0.6s ease, border-color 0.6s ease, box-shadow 0.6s ease",
    ...(state === "pending" && {
      background: alpha(stageColor, 0.06),
      border: `1px solid ${alpha(stageColor, 0.16)}`,
      color: alpha(stageColor, 0.42),
    }),
    ...(state === "active" && {
      background: alpha(stageColor, 0.14),
      border: `1px solid ${stageColor}`,
      color: stageColor,
      boxShadow: `0 0 16px ${alpha(stageColor, 0.18)}`,
    }),
    ...(state === "completed" && {
      background: stageColor,
      border: `1px solid ${stageColor}`,
      color: theme.palette.background.default,
      boxShadow: `0 0 18px ${alpha(stageColor, 0.34)}`,
    }),
  }),
  connector: (
    state: "pending" | "active" | "completed",
    stageColor: string,
    prevColor: string,
  ) => ({
    width: 2,
    minHeight: { xs: 42, md: 56 },
    flex: 1,
    my: 0.5,
    borderRadius: 1,
    transition: "background 0.6s ease",
    background:
      state === "completed"
        ? `linear-gradient(to bottom, ${alpha(stageColor, 0.54)}, ${alpha(prevColor, 0.4)})`
        : alpha(theme.palette.common.white, 0.12),
  }),
  rightColumn: (isLast: boolean) => ({
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    flex: 1,
    minWidth: 0,
    pt: 0.45,
    pb: isLast ? 0 : 0,
    mb: isLast ? 0 : 1,
    gap: 0.25,
    minHeight: 36,
  }),
  stageLabel: (
    state: "pending" | "active" | "completed",
    stageColor: string,
  ) => ({
    fontWeight: 700,
    lineHeight: 1.15,
    letterSpacing: "-0.02em",
    fontSize: { xs: "0.98rem", md: "1.06rem" },
    transition: "color 0.6s ease",
    color:
      state === "active" || state === "completed"
        ? stageColor
        : theme.palette.text.secondary,
  }),
  stageDescription: {
    color: alpha(theme.palette.text.secondary, 0.84),
    lineHeight: 1.6,
    fontSize: { xs: "0.8rem", md: "0.875rem" },
    fontWeight: 500,
    maxWidth: { xs: "none", md: 320 },
  },
});
