import { type Theme, alpha } from "@mui/material";

export const makeStyles = (theme: Theme) => ({
  card: {
    minHeight: { xs: "auto", md: "min(70vh, 600px)" },
    maxWidth: { xs: "100%", md: 1100 },
    mx: "auto",
    borderRadius: { xs: 4, md: 6 },
    py: { xs: 3, sm: 4, md: 5 },
    px: { xs: 2, sm: 4, md: 10 },
    position: "relative",
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
    gap: { xs: 3, md: 4 },
    background: `radial-gradient(circle at 20% 20%, ${alpha(theme.palette.primary.dark, 0.35)} 0%, transparent 55%), radial-gradient(circle at 80% 70%, ${alpha(theme.palette.purple.dark, 0.3)} 0%, transparent 55%), radial-gradient(circle at 50% 100%, ${alpha(theme.palette.secondary.dark, 0.4)} 0%, transparent 60%), ${alpha(theme.palette.background.paper, 0.6)}`,
    backdropFilter: "blur(16px)",
    border: `1px solid ${alpha(theme.palette.primary.light, 0.18)}`,
    boxShadow: `inset 0 1px 0 ${alpha(theme.palette.primary.light, 0.12)}, 0 24px 64px ${alpha("#000", 0.4)}`,
  },
  orb1: {
    position: "absolute",
    top: "-80px",
    right: "-60px",
    width: 320,
    height: 320,
    borderRadius: "50%",
    background: alpha(theme.palette.purple.main, 0.18),
    filter: "blur(60px)",
    zIndex: 0,
    pointerEvents: "none",
  },
  orb2: {
    position: "absolute",
    bottom: "-60px",
    left: "-40px",
    width: 280,
    height: 280,
    borderRadius: "50%",
    background: alpha(theme.palette.accent as string, 0.12),
    filter: "blur(50px)",
    zIndex: 0,
    pointerEvents: "none",
  },
  contentWrapper: {
    position: "relative",
    zIndex: 1,
  },
  eyebrow: {
    display: "block",
    textTransform: "uppercase",
    letterSpacing: "0.18em",
    color: theme.palette.text.primary as string,
    mb: 1.5,
    fontWeight: 600,
  },
  title: {
    fontWeight: 800,
    background: `linear-gradient(135deg, ${theme.palette.primary.light} 0%, ${theme.palette.purple.light} 50%, ${theme.palette.accent as string} 100%)`,
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
    backgroundClip: "text",
    mb: 1,
    lineHeight: 1.15,
  },
  subtitle: {
    color: theme.palette.text.primary,
  },
  bodyLayout: {
    position: "relative",
    zIndex: 1,
    display: "grid",
    gridTemplateColumns: { xs: "1fr", md: "minmax(0, 0.85fr) minmax(0, 1fr)" },
    gap: { xs: 3, md: 5 },
    alignItems: "center",
    flex: 1,
  },
  timelineWrapper: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    gap: 0,
    order: { xs: 2, md: 1 },
  },
  cardSwapStage: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    order: { xs: 1, md: 2 },
    width: "100%",
    height: { xs: 320, sm: 380, md: 560 },
    minHeight: { xs: 320, sm: 380, md: 560 },
    px: { xs: 0, sm: 1, md: 0 },
  },
  cardSwapInner: {
    position: "relative",
    width: 540,
    height: 380,
  },
  infoCard: (accent: string) => ({
    p: 4,
    width: "100%",
    height: "100%",
    position: "relative",
    display: "flex",
    flexDirection: "column",
    gap: 1.75,
    overflow: "hidden",
    borderRadius: 4,
    border: `1px solid ${alpha(accent, 0.22)}`,
    background: `
			radial-gradient(circle at 0% 0%, ${alpha(accent, 0.32)} 0%, transparent 55%),
			radial-gradient(circle at 100% 100%, ${alpha(accent, 0.16)} 0%, transparent 50%),
			linear-gradient(160deg, ${alpha(theme.palette.background.paper, 0.96)} 0%, ${alpha(theme.palette.background.default, 0.98)} 100%)
		`,
    boxShadow: `
			0 32px 72px -12px ${alpha("#000", 0.6)},
			0 0 0 1px ${alpha(accent, 0.08)} inset,
			0 0 80px ${alpha(accent, 0.12)} inset,
			0 12px 32px ${alpha(accent, 0.22)}
		`,
    color: theme.palette.text.primary,
  }),
  infoCardIcon: (accent: string) => ({
    width: 52,
    height: 52,
    borderRadius: 2.5,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: `linear-gradient(135deg, ${alpha(accent, 0.35)}, ${alpha(accent, 0.12)})`,
    border: `1px solid ${alpha(accent, 0.4)}`,
    color: accent,
    boxShadow: `0 8px 18px ${alpha(accent, 0.25)}`,
  }),
  infoCardTitle: (accent: string) => ({
    fontWeight: 700,
    color: alpha(accent, 0.95),
    letterSpacing: "-0.01em",
  }),
  infoCardBody: {
    color: theme.palette.text.primary,
    opacity: 0.85,
    lineHeight: 1.55,
  },
  stageRow: (state: "pending" | "active" | "completed") => ({
    display: "flex",
    flexDirection: "row",
    alignItems: "flex-start",
    opacity: state === "pending" ? 0.45 : 1,
    transition: "opacity 0.6s ease",
  }),
  leftColumn: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    mr: { xs: 1.75, md: 2.5 },
    flexShrink: 0,
  },
  dotWrapper: {
    position: "relative",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  outerHalo: (stageColor: string) => ({
    position: "absolute",
    width: 80,
    height: 80,
    borderRadius: "50%",
    background: alpha(stageColor, 0.25),
    zIndex: 0,
  }),
  innerHalo: (stageColor: string) => ({
    position: "absolute",
    width: 56,
    height: 56,
    borderRadius: "50%",
    background: alpha(stageColor, 0.35),
    zIndex: 0,
  }),
  dot: (state: "pending" | "active" | "completed", stageColor: string) => ({
    position: "relative",
    zIndex: 1,
    width: 36,
    height: 36,
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    transition:
      "background 0.6s ease, border-color 0.6s ease, box-shadow 0.6s ease",
    ...(state === "pending" && {
      background: alpha(stageColor, 0.08),
      border: `1px solid ${alpha(stageColor, 0.2)}`,
      color: alpha(stageColor, 0.5),
    }),
    ...(state === "active" && {
      background: alpha(stageColor, 0.18),
      border: `1px solid ${stageColor}`,
      color: stageColor,
    }),
    ...(state === "completed" && {
      background: stageColor,
      border: `1px solid ${stageColor}`,
      color: theme.palette.background.default,
      boxShadow: `0 0 18px ${alpha(stageColor, 0.55)}`,
    }),
  }),
  connector: (
    state: "pending" | "active" | "completed",
    stageColor: string,
    prevColor: string,
  ) => ({
    width: 2,
    minHeight: { xs: 42, md: 56 },
    flex: 1,
    my: 0.5,
    borderRadius: 1,
    transition: "background 0.6s ease",
    background:
      state === "completed"
        ? `linear-gradient(to bottom, ${alpha(stageColor, 0.6)}, ${alpha(prevColor, 0.6)})`
        : alpha(theme.palette.divider, 1),
  }),
  rightColumn: (isLast: boolean) => ({
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    pt: 0.5,
    pb: isLast ? 0 : 0,
    mb: isLast ? 0 : 1,
    gap: 0.25,
    minHeight: 36,
  }),
  stageLabel: (
    state: "pending" | "active" | "completed",
    stageColor: string,
  ) => ({
    fontWeight: 600,
    lineHeight: 1.25,
    fontSize: { xs: "0.95rem", md: "1rem" },
    transition: "color 0.6s ease",
    color:
      state === "active" || state === "completed"
        ? stageColor
        : theme.palette.text.secondary,
  }),
  stageDescription: {
    color: theme.palette.text.primary,
    lineHeight: 1.5,
    fontSize: { xs: "0.8rem", md: "0.875rem" },
    fontWight: 800,
  },
});
