import { aurora, auroraTint } from "@/shared/theme";

export const makeStyles = () => ({
  card: {
    minHeight: { xs: "auto", md: "min(54vh, 540px)" },
    maxWidth: { xs: "100%", md: 1160 },
    mx: "auto",
    borderRadius: { xs: aurora.radii.md, md: aurora.radii.card },
    py: { xs: 2.5, sm: 4, md: 4.5 },
    px: { xs: 1.5, sm: 4, md: 8 },
    position: "relative",
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
    gap: { xs: 3.5, md: 3.75 },
    background: `linear-gradient(168deg, oklch(0.235 0.026 262 / 0.92), oklch(0.175 0.026 262 / 0.82))`,
    border: `1px solid ${aurora.line}`,
    boxShadow: aurora.shadow.card,
    "&::before": {
      content: '""',
      position: "absolute",
      inset: 0,
      borderRadius: "inherit",
      background: `radial-gradient(circle at 16% 22%, ${auroraTint(aurora.status.concept, 0.16)} 0%, transparent 28%), radial-gradient(circle at 82% 76%, ${auroraTint(aurora.status.enrich, 0.12)} 0%, transparent 24%), linear-gradient(135deg, ${auroraTint(aurora.txHi, 0.04)} 0%, transparent 46%)`,
      pointerEvents: "none",
    },
  },
  orb1: {
    position: "absolute",
    top: "-42px",
    right: "-24px",
    width: 280,
    height: 180,
    borderRadius: "50%",
    background: auroraTint(aurora.status.enrich, 0.14),
    filter: "blur(54px)",
    transform: "rotate(-14deg)",
    zIndex: 0,
    pointerEvents: "none",
  },
  orb2: {
    position: "absolute",
    bottom: "-34px",
    left: "-12px",
    width: 240,
    height: 160,
    borderRadius: "50%",
    background: auroraTint(aurora.teal, 0.12),
    filter: "blur(48px)",
    transform: "rotate(18deg)",
    zIndex: 0,
    pointerEvents: "none",
  },
  contentWrapper: {
    position: "relative",
    zIndex: 1,
    maxWidth: 620,
    px: { xs: 0.5, sm: 0 },
  },
  eyebrow: {
    display: "inline-flex",
    alignItems: "center",
    gap: 10,
    textTransform: "uppercase",
    letterSpacing: "0.22em",
    color: aurora.txMid,
    fontFamily: aurora.font.mono,
    mb: 1.25,
    fontWeight: 700,
    "&::before": {
      content: '""',
      width: { xs: 24, sm: 36 },
      height: 1,
      borderRadius: 999,
      background: auroraTint(aurora.teal, 0.75),
    },
  },
  title: {
    fontFamily: aurora.font.display,
    fontWeight: 800,
    background: `linear-gradient(135deg, ${aurora.txHi} 0%, ${aurora.tx} 52%, ${aurora.teal} 100%)`,
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
    backgroundClip: "text",
    mb: 1,
    lineHeight: 1.04,
    letterSpacing: "-0.04em",
    maxWidth: 560,
    fontSize: { xs: "1.5rem", sm: "2rem", md: "2.5rem" },
  },
  subtitle: {
    color: aurora.txMid,
    fontFamily: aurora.font.ui,
    maxWidth: 520,
    lineHeight: 1.7,
    fontSize: { xs: "0.94rem", sm: "1rem" },
  },
  bodyLayout: {
    position: "relative",
    zIndex: 1,
    display: "grid",
    gridTemplateColumns: { xs: "1fr", md: "minmax(0, 0.76fr) minmax(0, 1fr)" },
    gap: { xs: 3.25, md: 3.5 },
    alignItems: "stretch",
    flex: 1,
  },
  timelineWrapper: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    gap: 0,
    order: { xs: 2, md: 1 },
    width: "100%",
    mt: { xs: 0.75, md: 0 },
    px: { xs: 1.25, sm: 0.5, md: 0 },
    pr: { md: 2 },
  },
  cardSwapStage: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    order: { xs: 1, md: 2 },
    width: "100%",
    height: { xs: 440, sm: 480, md: 480 },
    minHeight: { xs: 440, sm: 480, md: 480 },
    px: { xs: 0.25, sm: 1, md: 0 },
  },
  stageRow: (state: "pending" | "active" | "completed") => ({
    display: "flex",
    flexDirection: "row",
    alignItems: "flex-start",
    opacity: state === "pending" ? 0.45 : 1,
    transition: "opacity 0.6s ease, transform 0.6s ease",
  }),
  leftColumn: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    mr: { xs: 1.6, md: 2.2 },
    flexShrink: 0,
  },
  dotWrapper: {
    position: "relative",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  outerHalo: (stageColor: string) => ({
    position: "absolute",
    width: 72,
    height: 72,
    borderRadius: "50%",
    background: auroraTint(stageColor, 0.15),
    zIndex: 0,
  }),
  innerHalo: (stageColor: string) => ({
    position: "absolute",
    width: 50,
    height: 50,
    borderRadius: "50%",
    background: auroraTint(stageColor, 0.2),
    zIndex: 0,
  }),
  dot: (state: "pending" | "active" | "completed", stageColor: string) => ({
    position: "relative",
    zIndex: 1,
    width: 34,
    height: 34,
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    transition:
      "background 0.6s ease, border-color 0.6s ease, box-shadow 0.6s ease",
    ...(state === "pending" && {
      background: auroraTint(stageColor, 0.06),
      border: `1px solid ${auroraTint(stageColor, 0.16)}`,
      color: auroraTint(stageColor, 0.42),
    }),
    ...(state === "active" && {
      background: auroraTint(stageColor, 0.14),
      border: `1px solid ${stageColor}`,
      color: stageColor,
      boxShadow: `0 0 16px ${auroraTint(stageColor, 0.18)}`,
    }),
    ...(state === "completed" && {
      background: stageColor,
      border: `1px solid ${stageColor}`,
      color: aurora.tealInk,
      boxShadow: `0 0 18px ${auroraTint(stageColor, 0.34)}`,
    }),
  }),
  connector: (
    state: "pending" | "active" | "completed",
    stageColor: string,
    prevColor: string,
  ) => ({
    width: 2,
    minHeight: { xs: 42, md: 56 },
    flex: 1,
    my: 0.5,
    borderRadius: 1,
    transition: "background 0.6s ease",
    background:
      state === "completed"
        ? `linear-gradient(to bottom, ${auroraTint(stageColor, 0.54)}, ${auroraTint(prevColor, 0.4)})`
        : aurora.line2,
  }),
  rightColumn: (isLast: boolean) => ({
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    flex: 1,
    minWidth: 0,
    pt: 0.45,
    pb: isLast ? 0 : 0,
    mb: isLast ? 0 : 1,
    gap: 0.25,
    minHeight: 36,
  }),
  stageLabel: (
    state: "pending" | "active" | "completed",
    stageColor: string,
  ) => ({
    fontFamily: aurora.font.display,
    fontWeight: 700,
    lineHeight: 1.15,
    letterSpacing: "-0.02em",
    fontSize: { xs: "0.98rem", md: "1.06rem" },
    transition: "color 0.6s ease",
    color:
      state === "active" || state === "completed" ? stageColor : aurora.txMid,
  }),
  stageDescription: {
    color: aurora.txLow,
    fontFamily: aurora.font.ui,
    lineHeight: 1.6,
    fontSize: { xs: "0.8rem", md: "0.875rem" },
    fontWeight: 500,
    maxWidth: { xs: "none", md: 320 },
  },
});
