import { type Theme, alpha } from '@mui/material';

export const makeStyles = (theme: Theme) => ({
	pageHeader: {
		mb: 4,
		position: 'relative',
	},
	headerTitle: {
		fontWeight: 800,
		fontSize: { xs: '1.75rem', md: '2.5rem' },
		background: `linear-gradient(135deg, ${theme.palette.common.white} 0%, ${theme.palette.primary.light} 100%)`,
		backgroundClip: 'text',
		WebkitBackgroundClip: 'text',
		WebkitTextFillColor: 'transparent',
		mb: 1,
	},
	headerSubtitle: {
		color: theme.palette.text.secondary,
		fontSize: '1rem',
		maxWidth: '600px',
	},
	sectionTitle: {
		fontWeight: 700,
		mb: 3,
		display: 'flex',
		alignItems: 'center',
		gap: 1.5,
		position: 'relative',
		'&::after': {
			content: '""',
			position: 'absolute',
			bottom: -8,
			left: 0,
			width: 40,
			height: 3,
			borderRadius: 2,
			background: `linear-gradient(90deg, ${theme.palette.primary.main}, transparent)`,
		},
	},
	profileCard: {
		height: '100%',
		display: 'flex',
		flexDirection: 'column',
		background: alpha(theme.palette.background.paper, 0.4),
		backdropFilter: 'blur(12px)',
		border: `1px solid ${alpha(theme.palette.primary.light, 0.1)}`,
		transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
	},
	avatarWrapper: {
		position: 'relative',
		display: 'inline-block',
		mb: 3,
		'&:hover .avatar-overlay': {
			opacity: 1,
		},
	},
	avatar: {
		width: 140,
		height: 140,
		fontSize: '3rem',
		fontWeight: 700,
		background: `linear-gradient(135deg, ${alpha(theme.palette.primary.main, 0.2)}, ${alpha(theme.palette.primary.main, 0.05)})`,
		color: theme.palette.primary.light,
		border: `4px solid ${alpha(theme.palette.primary.light, 0.2)}`,
		boxShadow: `0 8px 32px ${alpha(theme.palette.primary.main, 0.2)}`,
	},
	avatarOverlay: {
		position: 'absolute',
		inset: 0,
		borderRadius: '50%',
		bgcolor: alpha(theme.palette.background.default, 0.6),
		backdropFilter: 'blur(4px)',
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'center',
		opacity: 0,
		transition: 'all 0.3s ease',
		cursor: 'pointer',
		border: `2px dashed ${alpha(theme.palette.primary.light, 0.5)}`,
	},
	detailRow: {
		display: 'flex',
		alignItems: 'center',
		flexWrap: 'wrap',
		gap: 2.5,
		py: 2.5,
		px: { xs: 2.5, md: 3 },
		borderRadius: 4,
		bgcolor: alpha(theme.palette.background.paper, 0.2),
		border: `1px solid ${alpha(theme.palette.divider, 0.05)}`,
		transition: 'all 0.2s ease',
		mb: 2,
		'&:last-child': { mb: 0 },
	},
	iconBox: (color: string) => ({
		width: { xs: 40, md: 48 },
		height: { xs: 40, md: 48 },
		borderRadius: 3,
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'center',
		bgcolor: alpha(color, 0.08),
		color: color,
		border: `1px solid ${alpha(color, 0.1)}`,
		flexShrink: 0,
		boxShadow: `0 4px 12px ${alpha(color, 0.1)}`,
	}),
	goalBox: {
		p: { xs: 2.5, md: 3 },
		borderRadius: 5,
		background: `linear-gradient(145deg, ${alpha(theme.palette.primary.main, 0.05)}, ${alpha(theme.palette.background.paper, 0.02)})`,
		border: `1px solid ${alpha(theme.palette.primary.light, 0.08)}`,
		position: 'relative',
		overflow: 'hidden',
		'&::before': {
			content: '""',
			position: 'absolute',
			top: 0,
			left: 0,
			width: '100%',
			height: '100%',
			background: `radial-gradient(circle at top right, ${alpha(theme.palette.primary.light, 0.05)}, transparent 70%)`,
			pointerEvents: 'none',
		},
	},
	actionButton: {
		borderRadius: 3,
		py: 1.5,
		px: { xs: 2, md: 4 },
		fontWeight: 700,
		minWidth: { xs: '100%', sm: 160 },
		textTransform: 'none',
		transition: 'all 0.2s cubic-bezier(0.4, 0, 0.2, 1)',
		'&:hover': {
			transform: 'translateY(-2px)',
			boxShadow: `0 4px 12px ${alpha(theme.palette.common.black, 0.1)}`,
		},
	},
});
