import { type Theme, type SxProps } from "@mui/material";
import { aurora as auroraPalette, auroraTint } from "@/shared/theme";

export const makeStyles = (_theme: Theme) => ({
  // ── Panel (mock .panel) ─────────────────────────────────────────────────
  panel: {
    position: "relative",
    overflow: "hidden",
    borderRadius: auroraPalette.radii.card,
    border: `1px solid ${auroraPalette.line}`,
    background:
      "linear-gradient(168deg, oklch(0.225 0.026 262 / 0.85), oklch(0.16 0.026 262 / 0.78))",
    boxShadow: auroraPalette.shadow.card,
    p: { xs: "22px 22px 24px", md: "28px 30px 30px" },
    height: "100%",
  } satisfies SxProps<Theme>,
  panelHead: {
    display: "flex",
    alignItems: "center",
    gap: 1.6,
  } satisfies SxProps<Theme>,
  panelHeadRow: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 2,
  } satisfies SxProps<Theme>,
  panelTitle: {
    fontFamily: auroraPalette.font.display,
    fontWeight: 700,
    fontSize: "21px",
    color: auroraPalette.txHi,
    letterSpacing: "-0.015em",
    m: 0,
  } satisfies SxProps<Theme>,
  panelUnderline: (accent: string = auroraPalette.teal) =>
    ({
      width: 56,
      height: 3,
      borderRadius: "999px",
      mt: 1.5,
      mb: 3,
      background: `linear-gradient(90deg, ${accent}, color-mix(in oklch, ${accent} 10%, transparent))`,
    }) satisfies SxProps<Theme>,
  panelIcon: (accent: string = auroraPalette.teal) =>
    ({
      width: 38,
      height: 38,
      borderRadius: "11px",
      display: "grid",
      placeItems: "center",
      background: `color-mix(in oklch, ${accent} 15%, ${auroraPalette.surface2})`,
      border: `1px solid ${auroraTint(accent, 0.26)}`,
      color: accent,
      flexShrink: 0,
    }) satisfies SxProps<Theme>,

  // ── Identity card ───────────────────────────────────────────────────────
  identityCard: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    textAlign: "center",
    pt: "38px",
    pb: "36px",
  } satisfies SxProps<Theme>,
  avatarWrapper: {
    position: "relative",
    width: 132,
    height: 132,
    borderRadius: "50%",
    display: "grid",
    placeItems: "center",
    mb: 2.75,
    "&::before": {
      content: '""',
      position: "absolute",
      inset: -3,
      borderRadius: "50%",
      background: `conic-gradient(from 200deg, ${auroraPalette.teal}, ${auroraPalette.status.concept}, ${auroraPalette.teal})`,
      opacity: 0.55,
      filter: "blur(2px)",
    },
    "&::after": {
      content: '""',
      position: "absolute",
      inset: 0,
      borderRadius: "50%",
      background: `radial-gradient(closest-side, ${auroraTint(auroraPalette.teal, 0.18)}, transparent 80%)`,
    },
    "&:hover .avatar-overlay": { opacity: 1 },
    "&:hover .avatar-remove": { opacity: 1, transform: "scale(1)" },
  } satisfies SxProps<Theme>,
  avatar: {
    position: "relative",
    zIndex: 1,
    width: 124,
    height: 124,
    fontFamily: auroraPalette.font.display,
    fontWeight: 800,
    fontSize: "54px",
    background: `radial-gradient(circle at 38% 30%, oklch(0.30 0.04 200), oklch(0.19 0.03 262))`,
    color: auroraPalette.teal,
    boxShadow: `0 0 40px -10px ${auroraTint(auroraPalette.teal, 0.5)}, 0 0 0 1px oklch(1 0 0 / 0.08) inset`,
  } satisfies SxProps<Theme>,
  avatarOverlay: {
    position: "absolute",
    inset: 0,
    borderRadius: "50%",
    bgcolor: "oklch(0.14 0.028 264 / 0.6)",
    backdropFilter: "blur(4px)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    opacity: 0,
    transition: "all 0.3s ease",
    cursor: "pointer",
    border: `2px dashed ${auroraTint(auroraPalette.teal, 0.5)}`,
    zIndex: 2,
  } satisfies SxProps<Theme>,
  identityName: {
    display: "inline-flex",
    alignItems: "center",
    gap: 1.1,
    fontFamily: auroraPalette.font.display,
    fontWeight: 700,
    fontSize: "26px",
    color: auroraPalette.txHi,
    letterSpacing: "-0.015em",
  } satisfies SxProps<Theme>,
  identityEmail: {
    mt: 0.9,
    fontFamily: auroraPalette.font.mono,
    fontSize: "13.5px",
    color: auroraPalette.txMid,
    wordBreak: "break-word",
  } satisfies SxProps<Theme>,
  roleChip: (accent: string) =>
    ({
      display: "inline-flex",
      alignItems: "center",
      gap: 1,
      mt: 2.5,
      px: 2,
      py: 1,
      borderRadius: "999px",
      fontFamily: auroraPalette.font.mono,
      fontSize: "11.5px",
      fontWeight: 600,
      letterSpacing: "0.1em",
      textTransform: "uppercase",
      background: auroraTint(accent, 0.1),
      border: `1px solid ${auroraTint(accent, 0.36)}`,
      color: accent,
      "& .MuiChip-icon, & .MuiChip-label": { color: accent },
      "& .MuiChip-icon": { ml: 0, mr: 0.5 },
    }) satisfies SxProps<Theme>,

  // ── Field rows (account details) ────────────────────────────────────────
  fieldRow: {
    display: "flex",
    alignItems: "center",
    gap: 2,
    p: "16px 18px",
    borderRadius: auroraPalette.radii.md,
    background: "oklch(0.27 0.022 262 / 0.4)",
    border: `1px solid ${auroraPalette.line}`,
    transition: "border-color .15s",
    "&:hover": { borderColor: auroraPalette.line2 },
  } satisfies SxProps<Theme>,
  fieldIcon: (accent: string = auroraPalette.teal) =>
    ({
      flex: "none",
      width: 44,
      height: 44,
      borderRadius: "12px",
      display: "grid",
      placeItems: "center",
      background: `color-mix(in oklch, ${accent} 14%, ${auroraPalette.surface2})`,
      border: `1px solid ${auroraTint(accent, 0.24)}`,
      color: accent,
    }) satisfies SxProps<Theme>,
  fieldLabel: {
    fontFamily: auroraPalette.font.mono,
    fontSize: "10.5px",
    fontWeight: 600,
    letterSpacing: "0.14em",
    textTransform: "uppercase",
    color: auroraPalette.txLow,
  } satisfies SxProps<Theme>,
  fieldValue: {
    fontSize: "16px",
    fontWeight: 600,
    color: auroraPalette.txHi,
    mt: 0.5,
    wordBreak: "break-word",
  } satisfies SxProps<Theme>,
  fieldEdit: {
    flex: "none",
    width: 36,
    height: 36,
    borderRadius: "10px",
    display: "grid",
    placeItems: "center",
    background: "transparent",
    border: `1px solid ${auroraPalette.line}`,
    color: auroraPalette.txMid,
    transition: "all .15s",
    "&:hover": {
      background: auroraTint(auroraPalette.teal, 0.1),
      borderColor: auroraTint(auroraPalette.teal, 0.4),
      color: auroraPalette.teal,
    },
  } satisfies SxProps<Theme>,

  // ── Goal block ──────────────────────────────────────────────────────────
  goalBox: {
    display: "flex",
    alignItems: "center",
    gap: 2,
    p: "18px 20px",
    borderRadius: auroraPalette.radii.md,
    background: "oklch(0.27 0.022 262 / 0.4)",
    border: `1px solid ${auroraPalette.line}`,
    flexWrap: { xs: "wrap", sm: "nowrap" },
  } satisfies SxProps<Theme>,
  goalIcon: {
    flex: "none",
    width: 46,
    height: 46,
    borderRadius: "12px",
    display: "grid",
    placeItems: "center",
    background: auroraTint(auroraPalette.teal, 0.13),
    border: `1px solid ${auroraTint(auroraPalette.teal, 0.28)}`,
    color: auroraPalette.teal,
  } satisfies SxProps<Theme>,
  goalTitle: {
    fontWeight: 700,
    fontSize: "16px",
    color: auroraPalette.txHi,
  } satisfies SxProps<Theme>,
  goalSub: {
    fontSize: "13px",
    color: auroraPalette.txMid,
    mt: 0.4,
  } satisfies SxProps<Theme>,
  emptyNote: {
    mt: 2,
    p: "18px 20px",
    borderRadius: auroraPalette.radii.md,
    border: `1px dashed ${auroraPalette.line2}`,
    background: "oklch(0.20 0.02 262 / 0.4)",
    fontSize: "14.5px",
    fontStyle: "italic",
    color: auroraPalette.txMid,
    textAlign: "center",
  } satisfies SxProps<Theme>,
  goalDisplay: {
    mt: 2,
    p: "18px 20px",
    borderRadius: auroraPalette.radii.md,
    background: "oklch(0.27 0.022 262 / 0.4)",
    border: `1px solid ${auroraPalette.line}`,
    color: auroraPalette.tx,
    lineHeight: 1.65,
    fontSize: "15px",
  } satisfies SxProps<Theme>,

  // ── Interests ───────────────────────────────────────────────────────────
  interestsLede: {
    color: auroraPalette.txMid,
    fontSize: "14.5px",
    lineHeight: 1.55,
    mb: 2,
  } satisfies SxProps<Theme>,
  interestEmpty: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 1.5,
    p: "30px 20px",
    borderRadius: auroraPalette.radii.md,
    border: `1px dashed ${auroraPalette.line2}`,
    background: "oklch(0.20 0.02 262 / 0.35)",
    textAlign: "center",
    mt: 0.75,
    "& p": {
      m: 0,
      color: auroraPalette.txMid,
      fontSize: "14px",
    },
  } satisfies SxProps<Theme>,
  interestEmptyIcon: {
    width: 46,
    height: 46,
    borderRadius: "12px",
    display: "grid",
    placeItems: "center",
    background: auroraPalette.surface2,
    border: `1px solid ${auroraPalette.line}`,
    color: auroraPalette.txLow,
  } satisfies SxProps<Theme>,
  interestChip: (isSelected: boolean, isEditing: boolean) => ({
    cursor: isEditing ? "pointer" : "default",
    fontFamily: auroraPalette.font.ui,
    fontSize: "13px",
    fontWeight: 600,
    height: 32,
    borderRadius: "999px",
    borderColor: isSelected
      ? auroraTint(auroraPalette.teal, 0.4)
      : auroraPalette.line,
    background: isSelected
      ? auroraTint(auroraPalette.teal, 0.14)
      : auroraPalette.surface2,
    color: isSelected ? auroraPalette.teal : auroraPalette.txMid,
    "& .MuiChip-icon": { color: "inherit", ml: 0.5 },
    "&:hover": isEditing
      ? {
          background: isSelected
            ? auroraTint(auroraPalette.teal, 0.22)
            : auroraTint(auroraPalette.teal, 0.08),
          borderColor: auroraTint(auroraPalette.teal, 0.4),
          color: isSelected ? auroraPalette.teal : auroraPalette.txHi,
        }
      : {},
  }),
  customInterestChip: {
    fontFamily: auroraPalette.font.ui,
    fontSize: "13px",
    fontWeight: 600,
    height: 32,
    borderRadius: "999px",
    background: auroraTint(auroraPalette.status.enrich, 0.18),
    border: `1px solid ${auroraTint(auroraPalette.status.enrich, 0.4)}`,
    color: auroraPalette.status.enrich,
    "& .MuiChip-deleteIcon": {
      color: auroraTint(auroraPalette.status.enrich, 0.7),
      "&:hover": { color: auroraPalette.status.enrich },
    },
  } satisfies SxProps<Theme>,

  // ── Buttons ────────────────────────────────────────────────────────────
  btnTealOutline: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 1.25,
    fontFamily: auroraPalette.font.ui,
    fontWeight: 600,
    fontSize: "14.5px",
    borderRadius: auroraPalette.radii.md,
    px: 2.5,
    py: 1.5,
    textTransform: "none",
    background: auroraTint(auroraPalette.teal, 0.08),
    border: `1px solid ${auroraTint(auroraPalette.teal, 0.4)}`,
    color: auroraPalette.teal,
    transition: "all .15s",
    "&:hover": {
      background: auroraTint(auroraPalette.teal, 0.16),
      borderColor: auroraTint(auroraPalette.teal, 0.55),
    },
    "&.Mui-disabled": {
      opacity: 0.5,
      color: auroraPalette.teal,
    },
  } satisfies SxProps<Theme>,
  btnTealSolid: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 1.25,
    fontFamily: auroraPalette.font.ui,
    fontWeight: 700,
    fontSize: "14.5px",
    borderRadius: auroraPalette.radii.md,
    px: 2.5,
    py: 1.5,
    textTransform: "none",
    background: `linear-gradient(150deg, ${auroraPalette.teal}, ${auroraPalette.tealDeep})`,
    border: "1px solid transparent",
    color: auroraPalette.tealInk,
    boxShadow: `0 12px 28px -14px ${auroraTint(auroraPalette.teal, 0.7)}`,
    "&:hover": {
      transform: "translateY(-1px)",
      boxShadow: `0 16px 34px -14px ${auroraTint(auroraPalette.teal, 0.85)}`,
    },
    "&.Mui-disabled": {
      opacity: 0.55,
      color: auroraPalette.tealInk,
    },
  } satisfies SxProps<Theme>,
  btnGhost: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 1.25,
    fontFamily: auroraPalette.font.ui,
    fontWeight: 600,
    fontSize: "14.5px",
    borderRadius: auroraPalette.radii.md,
    px: 2.5,
    py: 1.5,
    textTransform: "none",
    background: "transparent",
    border: `1px solid ${auroraPalette.line}`,
    color: auroraPalette.txMid,
    transition: "all .15s",
    "&:hover": {
      background: auroraPalette.surface2,
      borderColor: auroraPalette.line2,
      color: auroraPalette.txHi,
    },
  } satisfies SxProps<Theme>,

  // ── Security rows ──────────────────────────────────────────────────────
  secRow: (accent: string, danger?: boolean) =>
    ({
      display: "flex",
      alignItems: { xs: "flex-start", sm: "center" },
      flexDirection: { xs: "column", sm: "row" },
      justifyContent: "space-between",
      gap: 2.5,
      p: "22px 24px",
      borderRadius: auroraPalette.radii.md,
      border: danger
        ? `1px solid ${auroraTint(auroraPalette.status.fail, 0.3)}`
        : `1px solid color-mix(in oklch, ${accent} 22%, ${auroraPalette.line})`,
      background: danger
        ? auroraTint(auroraPalette.status.fail, 0.07)
        : `color-mix(in oklch, ${accent} 5%, oklch(0.20 0.024 262 / 0.5))`,
    }) satisfies SxProps<Theme>,
  secRowTitle: (accent: string) =>
    ({
      m: 0,
      fontSize: "16px",
      fontWeight: 700,
      color: accent,
    }) satisfies SxProps<Theme>,
  secRowDesc: {
    mt: 0.6,
    fontSize: "13.5px",
    color: auroraPalette.txMid,
  } satisfies SxProps<Theme>,
  btnAccentOutline: (accent: string) =>
    ({
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      gap: 1.25,
      fontFamily: auroraPalette.font.ui,
      fontWeight: 600,
      fontSize: "14.5px",
      borderRadius: auroraPalette.radii.md,
      px: 2.5,
      py: 1.5,
      textTransform: "none",
      background: "transparent",
      border: `1px solid color-mix(in oklch, ${accent} 45%, transparent)`,
      color: accent,
      flexShrink: 0,
      width: { xs: "100%", sm: 200 },
      transition: "all .15s",
      "&:hover": {
        background: `color-mix(in oklch, ${accent} 12%, transparent)`,
        borderColor: `color-mix(in oklch, ${accent} 65%, transparent)`,
      },
      "&.Mui-disabled": { opacity: 0.55, color: accent },
    }) satisfies SxProps<Theme>,
  btnDanger: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 1.25,
    fontFamily: auroraPalette.font.ui,
    fontWeight: 700,
    fontSize: "14.5px",
    borderRadius: auroraPalette.radii.md,
    px: 2.5,
    py: 1.5,
    textTransform: "none",
    background: auroraPalette.status.fail,
    border: "1px solid transparent",
    color: "oklch(0.18 0.03 20)",
    flexShrink: 0,
    width: { xs: "100%", sm: 200 },
    boxShadow: `0 12px 28px -14px ${auroraTint(auroraPalette.status.fail, 0.8)}`,
    "&:hover": {
      transform: "translateY(-1px)",
      boxShadow: `0 16px 34px -14px ${auroraTint(auroraPalette.status.fail, 0.9)}`,
    },
  } satisfies SxProps<Theme>,
});
