import { type Theme, alpha } from '@mui/material';

export const makeStyles = (theme: Theme) => ({
	wrapper: {
		mb: 4,
	},
	card: {
		position: 'relative',
		overflow: 'hidden',
		borderRadius: 6,
		p: { xs: 4, md: 6 },
		background: alpha(theme.palette.background.paper, 0.4),
		backdropFilter: 'blur(12px)',
		border: `1px solid ${alpha(theme.palette.info.light, 0.1)}`,
	},
	accentBar: {
		position: 'absolute',
		top: 0,
		left: 0,
		right: 0,
		height: 4,
		background: `linear-gradient(90deg, ${theme.palette.info.main}, ${theme.palette.secondary.main}, ${theme.palette.primary.main})`,
	},
	orbTopRight: {
		position: 'absolute',
		top: -80,
		right: -80,
		width: 260,
		height: 260,
		borderRadius: '50%',
		background: `radial-gradient(circle, ${alpha(theme.palette.info.main, 0.2)} 0%, transparent 70%)`,
		pointerEvents: 'none',
	},
	orbBottomLeft: {
		position: 'absolute',
		bottom: -60,
		left: -60,
		width: 200,
		height: 200,
		borderRadius: '50%',
		background: `radial-gradient(circle, ${alpha(theme.palette.secondary.main, 0.12)} 0%, transparent 70%)`,
		pointerEvents: 'none',
	},
	title: {
		fontWeight: 900,
		mb: 1.5,
		fontSize: { xs: '1.75rem', sm: '2.25rem' },
		lineHeight: 1.2,
		background: `linear-gradient(135deg, ${theme.palette.info.light} 0%, ${theme.palette.secondary.main} 50%, ${theme.palette.primary.light} 100%)`,
		backgroundClip: 'text',
		WebkitBackgroundClip: 'text',
		WebkitTextFillColor: 'transparent',
		overflow: 'hidden',
		textOverflow: 'ellipsis',
		whiteSpace: 'nowrap',
	},
	chipRow: {
		display: 'flex',
		alignItems: 'center',
		gap: 1.5,
		mb: 2,
		flexWrap: 'wrap',
	},
	topicChip: {
		bgcolor: alpha(theme.palette.primary.main, 0.1),
		color: theme.palette.primary.light,
		fontWeight: 500,
	},
	difficultyChip: {
		borderColor: alpha(theme.palette.warning.main, 0.3),
		color: theme.palette.warning.light,
		fontSize: '0.7rem',
	},
	conceptChip: {
		bgcolor: alpha(theme.palette.info.main, 0.1),
		color: theme.palette.info.light,
		fontWeight: 500,
		'& .MuiChip-icon': { color: 'inherit' },
	},
	metaRow: {
		display: 'flex',
		gap: 3,
		flexWrap: 'wrap',
		alignItems: 'center',
		mb: 3,
	},
	metaItem: {
		display: 'flex',
		alignItems: 'center',
		gap: 1,
	},
	actionRow: {
		display: 'flex',
		gap: 1.5,
		flexWrap: 'wrap',
	},
});
