import { aurora, auroraTint } from "@/shared/theme";

export const styles = {
  card: {
    p: { xs: 2.5, md: "28px 30px 30px" },
    position: "relative" as const,
    overflow: "hidden" as const,
  },
  aura: {
    position: "absolute" as const,
    top: "-50%",
    right: "-6%",
    width: "40%",
    height: "110%",
    background: `radial-gradient(closest-side, ${auroraTint(aurora.status.enrich, 0.18)}, transparent 75%)`,
    filter: "blur(26px)",
    pointerEvents: "none" as const,
    zIndex: 0,
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "16px",
    mb: "20px",
    position: "relative" as const,
    zIndex: 1,
    flexWrap: "wrap" as const,
  },
  titleWrap: {
    display: "flex",
    alignItems: "center",
    gap: "14px",
    minWidth: 0,
  },
  titleIcon: {
    width: 46,
    height: 46,
    borderRadius: "13px",
    display: "grid",
    placeItems: "center",
    background: `linear-gradient(150deg, ${auroraTint(aurora.status.enrich, 0.25)}, ${auroraTint(aurora.status.concept, 0.18)})`,
    border: `1px solid ${auroraTint(aurora.status.enrich, 0.35)}`,
    color: aurora.status.enrich,
    boxShadow: `0 0 26px -8px ${auroraTint(aurora.status.enrich, 0.6)}`,
    flex: "none",
  },
  title: {
    fontFamily: aurora.font.display,
    fontWeight: 700,
    fontSize: "22px",
    color: aurora.txHi,
    letterSpacing: "-0.015em",
    m: 0,
  },
  meta: {
    fontFamily: aurora.font.mono,
    fontSize: "11.5px",
    color: aurora.txLow,
    mt: "4px",
    display: "inline-flex",
    alignItems: "center",
    gap: "7px",
  },
  feedLink: {
    display: "inline-flex",
    alignItems: "center",
    gap: "7px",
    color: aurora.status.enrich,
    fontSize: "14px",
    fontWeight: 600,
    textDecoration: "none",
    whiteSpace: "nowrap" as const,
    "&:hover": { color: auroraTint(aurora.status.enrich, 0.85) },
  },
  grid: {
    position: "relative" as const,
    zIndex: 1,
  },
};
