import { alpha } from "@mui/material";
import { palette } from "@/shared/theme";

export const styles = {
  card: {
    p: 2.5,
    height: "100%",
    display: "flex",
    flexDirection: "column",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    mb: 2,
  },
  title: {
    fontWeight: 600,
    display: "flex",
    alignItems: "center",
    gap: 1.5,
  },
  titleIcon: {
    p: 0.8,
    borderRadius: 1.5,
    bgcolor: alpha(palette.info.main, 0.1),
    display: "flex",
    color: palette.info.main,
  },
  feedLink: {
    color: palette.info.light,
    display: "flex",
    alignItems: "center",
    gap: 0.5,
    cursor: "pointer",
    fontWeight: 500,
    "&:hover": { color: palette.info.main },
  },
  articleCard: (color: string) => ({
    bgcolor: alpha(color, 0.05),
    border: `1px solid ${alpha(color, 0.1)}`,
    borderRadius: 2.5,
    p: 1.5,
    textDecoration: "none",
    height: "100%",
    "&:hover": {
      bgcolor: alpha(color, 0.08),
      borderColor: color,
      transform: "translateY(-3px)",
      boxShadow: `0 6px 14px ${alpha(color, 0.1)}`,
      "& .news-arrow": { opacity: 1 },
    },
  }),
  articleHeader: {
    p: 0,
    pb: 0,
    marginBottom: -4,
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  articleIconBox: (color: string) => ({
    width: 50,
    height: 50,
    borderRadius: 1.5,
    bgcolor: alpha(color, 0.15),
    color,
  }),
  articleContent: {
    p: 0,
    flexGrow: 1,
  },
  sourceBadge: {
    px: 0.8,
    py: 0.3,
    borderRadius: 1,
    bgcolor: alpha(palette.text.primary, 0.04),
    fontSize: "0.8rem",
    fontWeight: 600,
    color: "text.secondary",
  },
  categoryLabel: (color: string) => ({
    fontSize: "0.65rem",
    fontWeight: 800,
    color,
    textTransform: "uppercase",
    letterSpacing: "0.6px",
    mb: 0.25,
  }),
  articleTitle: {
    fontWeight: 700,
    fontSize: "0.825rem",
    lineHeight: 1.35,
    color: "text.primary",
    mb: 0.25,
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
  },
  articleDescription: {
    color: "text.secondary",
    fontSize: "0.75rem",
    lineHeight: 1.4,
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
  },
  externalIcon: {
    position: "absolute",
    bottom: 8,
    right: 8,
    opacity: 0,
    transition: "all 0.3s ease",
  },
  skeletonCard: {
    p: 1.5,
    borderRadius: 2.5,
    bgcolor: alpha(palette.text.primary, 0.02),
    border: `1px solid ${alpha(palette.text.primary, 0.05)}`,
    display: "flex",
    flexDirection: "column",
    gap: 0.75,
  },
};
