import { Theme, alpha } from '@mui/material';

export const makeStyles = (statusColor: string, theme: Theme) => ({
	card: {
		cursor: 'pointer',
		transition: 'all 0.45s cubic-bezier(0.23, 1, 0.32, 1)',
		position: 'relative',
		overflow: 'hidden',
		'&:hover': {
			transform: 'translateY(-10px)',
			boxShadow: `0 24px 48px -12px ${alpha(statusColor, 0.2)}`,
			'& .arrow-icon': {
				transform: 'translateX(6px)',
				color: statusColor,
				opacity: 1,
			},
		},
		'& .arrow-icon': {
			transition: 'all 0.45s cubic-bezier(0.23, 1, 0.32, 1)',
			opacity: 0.5,
		},
		'&::before': {
			content: '""',
			position: 'absolute',
			top: 0,
			left: 0,
			width: '4px',
			height: '100%',
			bgcolor: statusColor,
			opacity: 0.8,
			transition: 'width 0.3s ease',
		},
		'&:hover::before': {
			width: '6px',
		},
	},
	header: {
		display: 'flex',
		justifyContent: 'space-between',
		gap: 3,
		mb: 2.5,
	},
	headerContent: {
		flex: 1,
		minWidth: 0,
	},
	titleContainer: {
		display: 'flex',
		alignItems: 'center',
		gap: 1.5,
		mb: 1,
	},
	title: {
		fontWeight: 700,
		fontSize: '1.25rem',
		lineHeight: 1.3,
		color: theme.palette.text.primary,
		display: '-webkit-box',
		WebkitLineClamp: 2,
		WebkitBoxOrient: 'vertical',
		overflow: 'hidden',
	},
	description: {
		color: theme.palette.text.secondary,
		fontSize: '0.925rem',
		lineHeight: 1.5,
		display: '-webkit-box',
		WebkitLineClamp: 2,
		WebkitBoxOrient: 'vertical',
		overflow: 'hidden',
	},
	progressContainer: {
		position: 'relative',
		flexShrink: 0,
		width: 64,
		height: 64,
	},
	progressTrack: {
		position: 'absolute',
		color: alpha(theme.palette.divider, 0.1),
	},
	progressValue: {
		position: 'absolute',
		color: statusColor,
		strokeLinecap: 'round',
	},
	progressCenter: {
		position: 'absolute',
		inset: 0,
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'center',
	},
	progressText: {
		fontWeight: 800,
		color: statusColor,
		fontSize: '0.85rem',
	},
	statusBadge: {
		mb: 2.5,
	},
	statusChip: {
		height: 26,
		fontSize: '0.75rem',
		fontWeight: 700,
		textTransform: 'uppercase',
		letterSpacing: '0.05em',
		bgcolor: alpha(statusColor, 0.12),
		color: statusColor,
		borderRadius: '6px',
	},
	statsRow: {
		display: 'flex',
		gap: 3,
		flexWrap: 'wrap',
		mb: 2.5,
	},
	statItem: {
		display: 'flex',
		alignItems: 'center',
		gap: 1,
	},
	statText: {
		color: theme.palette.text.primary,
		fontWeight: 500,
		fontSize: '0.875rem',
	},
	difficultyRow: {
		display: 'flex',
		gap: 1,
		flexWrap: 'wrap',
	},
	difficultyChip: {
		height: 24,
		fontSize: '0.75rem',
		fontWeight: 600,
		borderRadius: '4px',
	},
	footerContent: {
		display: 'flex',
		justifyContent: 'space-between',
		alignItems: 'center',
		pt: 1,
	},
	footerInfo: {
		display: 'flex',
		gap: 2,
		alignItems: 'center',
	},
	paceChip: {
		height: 24,
		fontSize: '0.75rem',
		fontWeight: 600,
		bgcolor: alpha(theme.palette.info.main, 0.1),
		color: theme.palette.info.light,
		borderRadius: '4px',
	},
	relativeTime: {
		color: theme.palette.text.secondary,
		fontSize: '0.8rem',
		fontWeight: 500,
	},
});
