import { type Theme, alpha, type SxProps } from '@mui/material';

export const makeStyles = (theme: Theme) => ({
	loadingContainer: {
		display: 'flex',
		justifyContent: 'center',
		py: 2,
	},
	emptyText: {
		color: theme.palette.text.secondary,
		fontStyle: 'italic',
		py: 1,
	},
	sectionTitle: {
		color: theme.palette.text.secondary,
		fontWeight: 600,
		textTransform: 'uppercase',
		letterSpacing: 0.5,
		mb: 1.5,
		display: 'block',
	},
	resourcesList: {
		display: 'flex',
		flexDirection: 'column',
		gap: 1.5,
	},
	resourceLink: {
		display: 'flex',
		alignItems: 'flex-start',
		gap: { xs: 1, sm: 1.5 },
		p: { xs: 1.25, sm: 1.75 },
		borderRadius: 3,
		bgcolor: alpha(theme.palette.background.paper, 0.5),
		border: `1px solid ${alpha(theme.palette.divider, 0.3)}`,
		transition: 'all 0.2s ease',
		cursor: 'pointer',
		textDecoration: 'none',
		'&:hover': {
			bgcolor: alpha(theme.palette.primary.main, 0.06),
			borderColor: alpha(theme.palette.primary.main, 0.2),
			transform: { xs: 'none', sm: 'translateX(4px)' },
		},
	},
	iconContainer: (color: string) => ({
		width: { xs: 32, sm: 36 },
		height: { xs: 32, sm: 36 },
		borderRadius: 2,
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'center',
		bgcolor: alpha(color, 0.1),
		color: color,
		flexShrink: 0,
	}),
	resourceTitle: {
		color: theme.palette.text.primary,
		fontWeight: 600,
		fontSize: { xs: '0.9rem', sm: '1rem' },
		lineHeight: 1.3,
	},
	description: {
		color: theme.palette.text.secondary,
		fontSize: '0.85rem',
		lineHeight: 1.5,
		display: '-webkit-box',
		WebkitLineClamp: 2,
		WebkitBoxOrient: 'vertical',
		overflow: 'hidden',
		mt: 0.25,
	},
	chipRow: {
		display: 'flex',
		gap: 0.75,
		mt: 1,
		flexWrap: 'wrap',
	},
	providerChip: {
		height: 20,
		fontSize: '0.65rem',
		bgcolor: alpha(theme.palette.text.secondary, 0.1),
		color: theme.palette.text.secondary,
	},
	difficultyChip: (color: string) => ({
		height: 20,
		fontSize: '0.65rem',
		bgcolor: alpha(color, 0.1),
		color: color,
	}),
});
